CREATE DATABASE IF NOT EXISTS board_game_simulator CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE board_game_simulator;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(64) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
